project:
  type: website
  output-dir: docs

website:
  title: "Dimash Alchinbayev"
  google-analytics: "G-5WV6Y7EFV3"
  navbar:
    left:
      - href: index.qmd
        text: CV
      - projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



